name: CI / Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          pip install --no-cache-dir flake8 mypy pytest pytest-asyncio httpx

      - name: Lint with flake8
        run: flake8 .

      - name: Type-check with mypy
        run: mypy .

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: lint-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build image
        run: docker build --pull -t api-football-smartbets:ci-${{ github.sha }} .
